pipeline:
    start:
        image: node:11.14.0
        commands:
            - echo "Starting CI deploy"
            - echo "Machine $HOSTNAME"
            # Replace this with some api calls

    install:
        image: node:11.14.0
        commands:
            - echo "Installing modules from NPM"
            - echo "Machine $HOSTNAME"
            # Replace this with some api calls ^
            - npm install

    build:
        image: node:11.14.0
        commands:
            - echo "Building Vue Project"
            - echo "Machine $HOSTNAME"
            # Replace this with some api calls ^
            - npm run build

    deploy:
        image: node:11.14.0
        secrets: [ SSH_KEY, SSH_USER, SSH_HOST, SSH_PORT, SITE_DIRECTORY ]
        commands:
            - echo "Deploying via SSH to target host"
            - echo "Machine $HOSTNAME"
            # Replace this with some api calls ^
            
            # Install required packages
            - apt update -y
            - apt install rsync -y
            
            # Put SSH key on system, set permissions, and keyscan
            - mkdir ~/.ssh -p
            - echo "-----BEGIN RSA PRIVATE KEY-----\n$(echo $SSH_KEY | tr " " "\n" | tail -n +5 | head -n -4)\n-----END RSA PRIVATE KEY-----" > ~/.ssh/deploy_id_rsa
            - chmod 0600 ~/.ssh/deploy_id_rsa
            - ssh-keyscan -H $SSH_HOST -p $SSH_PORT >> ~/.ssh/known_hosts
                                            
            # Delete old site directory with SSH command
            - ssh $SSH_USER@$SSH_HOST -p $SSH_PORT -i ~/.ssh/deploy_id_rsa "rm -rf $SITE_DIRECTORY && mkdir $SITE_DIRECTORY"

            # Create new site directory and rsync it over
            - rsync -rv -e "ssh -p $SSH_PORT -i ~/.ssh/deploy_id_rsa" ./dist/* $SSH_USER@$SSH_HOST:$SITE_DIRECTORY

            # Delete SSH key from system
            - rm ~/.ssh/deploy_id_rsa

            - echo "Deploy complete"
            # Replace this with some api calls ^
