apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: app
spec:
  type: LoadBalancer
  loadBalancerIP: "35.197.71.58"
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: gcr.io/dustinrouillard/app:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
